name: MoonBit CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1
          
      - name: MoonBit Check
        run: moon check --deny-warn
        
      - name: MoonBit Format Check
        run: moon fmt --check

      - name: MoonBit Info Check
        run: moon info

      - name: MoonBit Build
        run: moon build
        
      - name: MoonBit Test
        run: moon test --deny-warn

