name: MoonBit Package Check

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup latest MoonBit CLI
        uses: hustcer/setup-moonbit@v1
        with:
          version: "latest"
      - name: Verify package
        run: |
          moon version --all
          moon check --deny-warn
          moon fmt --check
          moon info
          git diff --exit-code
          moon build
          moon test --deny-warn
          moon publish --dry-run
